counter_show_site_counter: 1
counter_show_unique_visitor: 1
counter_registered_user: 1
counter_unregistered_user: 1
counter_blocked_user: 1
counter_published_node: 1
counter_unpublished_node: 1
counter_show_server_ip: 1
counter_show_ip: 1
counter_show_counter_since: 1
counter_statistic_today: 1
counter_statistic_week: 1
counter_statistic_month: 1
counter_statistic_year: 1
counter_skip_admin: 0
counter_refresh_delay: 10
counter_insert_delay: 1
counter_initial_counter: 0
counter_initial_unique_visitor: 0
counter_initial_since: 0
